# Generated by Django 2.0 on 2018-04-08 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard', max_length=200)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('has_voted', models.BooleanField)
            ],
        ),
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('name')},
        ),
    ]
