# Generated by Django 4.1 on 2023-11-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_census_users_alter_census_name_delete_foe'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
