# Generated by Django 4.1 on 2023-11-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_census_has_voted'),
        ('voting', '0005_voting_census'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='census',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='census_id', to='census.census'),
        ),
    ]
